version: "3.8"

services:
  devcontainer:
    image: ghcr.io/chalmersproject/signal-monitor-server-devcontainer
    build:
      context: .
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: signal_monitor
      DATABASE_URL: postgresql://postgres:password@postgres/signal_monitor
    command: sleep infinity
    volumes:
      - ../..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker:/root/.docker
      - vscode-extensions:/root/.vscode-server/extensions
      - yarn-cache:/usr/local/share/.cache/yarn/v6
      - cargo-cache-git:/usr/local/cargo/git
      - cargo-cache-registry:/usr/local/cargo/registry
      - server-target:/workspace/server/target
      - server-app-node_modules:/workspace/server/app/node_modules
    ports:
      - 3000:3000

  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: signal_monitor
      POSTGRES_PASSWORD: password

volumes:
  vscode-extensions:
  yarn-cache:
  cargo-cache-git:
  cargo-cache-registry:
  server-target:
  server-app-node_modules:
  postgres:
